name: Build and Test

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod vendor

#      - name: Test token
#        run: echo ${{ secrets.HAHA_SECRET }}
#        run: echo ${{ secrets.CODECOV_TOKEN }}
      - name: Test
        run: go test -v .

# If it does not has the main function and doesn't need to build.
#      - name: Build
#        run: go build -v .